// PRODUCTS
export const REQUEST_PRODUCTS_PENDING = 'REQUEST_PRODUCTS_PENDING';
export const REQUEST_PRODUCTS_SUCCESS = 'REQUEST_PRODUCTS_SUCCESS';
export const REQUEST_PRODUCTS_FAILED = 'REQUEST_PRODUCTS_FAILED';

// PRODUCT
export const REQUEST_PRODUCT_PENDING = 'REQUEST_PRODUCT_PENDING';
export const REQUEST_PRODUCT_SUCCESS = 'REQUEST_PRODUCT_SUCCESS';
export const REQUEST_PRODUCT_FAILED = 'REQUEST_PRODUCT_FAILED';

// CART
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SUBTRACT_QUANTITY = 'SUBTRACT_QUANTITY';
export const ADD_QUANTITY = 'ADD_QUANTITY';
